### ISSUE TITLE
Some problems about MXNetError

### ISSUE THREAD

**Issue by Naturallyyeyeye** [microsoft/MaskFlownet#21]
Hi,
   When I run the main.py with "MaskFlownet_S_sintel.yaml --dataset_cfg sintel_kitti2015_hd1k.yaml -g 0 -c dbbSep30-1206 --clear_steps", i got the error like below:
Traceback (most recent call last):
  File "/MaskFlownet-master/main.py", line 537, in <module>
    train_log = pipe.train_batch(img1, img2, flow, geo_aug, color_aug, mask = mask)
  File "/MaskFlownet-master/network/pipeline.py", line 101, in train_batch
    img1s, img2s, labels, masks = geo_aug(img1s, img2s, labels, masks)
  File "/anaconda3/envs/maskflownet2/lib/python3.6/site-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/anaconda3/envs/maskflownet2/lib/python3.6/site-packages/mxnet/gluon/block.py", line 915, in forward
    return self._call_cached_op(x, *args)
  File "/anaconda3/envs/maskflownet2/lib/python3.6/site-packages/mxnet/gluon/block.py", line 821, in _call_cached_op
    out = self._cached_op(*cargs)
  File "/anaconda3/envs/maskflownet2/lib/python3.6/site-packages/mxnet/_ctypes/ndarray.py", line 150, in __call__
    ctypes.byref(out_stypes)))
  File "/anaconda3/envs/maskflownet2/lib/python3.6/site-packages/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator geometryaugmentation0_bilinearsampler0: [14:00:56] src/operator/./bilinear_sampler-inl.h:158: Check failed: dshape[0] == lshape[0] (1 vs. 4) : 
   Can I ask for a help? Thank you very much in advance.

**Comment by simon1727** [comment]
Hi Naturallyyeyeye, thanks for your interest in our work.

I have never met this problem. What's your MXNet version?

**Comment by Naturallyyeyeye** [comment]
> Hi Naturallyyeyeye, thanks for your interest in our work.
> 
> I have never met this problem. What's your MXNet version?

I install mxnet with the code in terminal as follows:pip install mxnet-cu101==1.5 -i https://pypi.tuna.tsinghua.edu.cn/simple.
